### ISSUE TITLE
How to translate the engine?

### ISSUE THREAD

**Issue by JaxonShao** [TorqueGameEngines/Torque3D#1035]
I want to translate the engine into Chinese, which files should I translate？

**Comment by Azaezel** [comment]
It's been... a significant amount of time since there's been review on that front, however from the internal documentation:
one would first inject [textids](https://github.com/TorqueGameEngines/Torque3D/blob/cf233367a84ac35462b577c3227a105c2a8d3882/Engine/source/gui/controls/guiTextCtrl.cpp#L43) into text gui elements
one would then generate a [LangTable](https://github.com/TorqueGameEngines/Torque3D/blob/cf233367a84ac35462b577c3227a105c2a8d3882/Engine/source/i18n/lang.cpp#L211-L222) file which is effectively a key/pair list, then trigger it's usage with [setCoreLangTable ](https://github.com/TorqueGameEngines/Torque3D/blob/cf233367a84ac35462b577c3227a105c2a8d3882/Engine/source/i18n/i18n.cpp#L72-L86)

Another user was kind enough to provide an example of a langtable file https://github.com/OTHGMars/Torque3D-1/commit/8045c3fc34e5665035cab7a361c21a12604a0ef0
