### ISSUE TITLE
Why my localization test which GUI label does not update？ ps：a little bit important

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/Torque3D#1036]
hi.im examining new engine：torque nowdays，everything looks fine except my localization functionality test process。and where is the issues？
want get community‘s help！！！
step1：file：cn.txt;
![file](https://github.com/TorqueGameEngines/Torque3D/assets/109895629/70b04831-82bd-49df-914e-b22e6c9b565c)

step2：engine setup
![engine detail](https://github.com/TorqueGameEngines/Torque3D/assets/109895629/0c93c24e-e9b0-4732-b320-2b73a0f681b6)

step3：script edit at “main.cs or main.tscript"
![script detail](https://github.com/TorqueGameEngines/Torque3D/assets/109895629/ef2ca4de-13af-4fbf-a2fc-8ea3fe737686)

step4:   console output

![console detail](https://github.com/TorqueGameEngines/Torque3D/assets/109895629/bec695db-1be7-4c1c-8149-220f5e7be89b)

**Comment by dottools** [comment]
### Torque uses zero-based indexes

`LangTable` class `setCurrentLanguage(U32 id)` function is zero-based indexed (starts from 0, not 1). Meaning when you added the languages the following language table was built before `setCurrentLanguage(1);` call:

| id | name | filename |
|--|-----|----|
| 0 | cn | cn.txt |
| 1 | en | en.txt |

When you did `%mytable.addLanguage("cn.txt", "cn");` it automatically set "cn" as your default language, because there were no previous entries in the language table, as it reported in console:
```
Language cn [cn.txt] activated.
```

Then when you called `%mytable.addLanguage("en.txt", "en");` it just added it to the language table and did not implicitly make it the set language.

However when you called `setCurrentLanguage(1);` then it shows in console that you switched from lang id=0 (cn) to lang id=1 (en) with the following console message:
```
Language en [en.txt] activated.
```

### Tools missing
But there might be a bigger problem. According to [this localization tutorial](https://torque-3d.readthedocs.io/en/latest/script/localization.html) you're suppose to compile the language text files (cn.txt, en.txt) into .lso files (compiled string lookup table) using a `langc` tool. But `langc`'s source files are missing in Torque 3D and the tool doesn't come precompiled.

So even if you correct the langID index usage issue the biggest problem is the language table code still requires a compiled `.lso` language file.

**Comment by Azaezel** [comment]
*very* rough first draft based on https://torque3d.org/forums/topic/618-how-setting-languages-countries-into-a-t3d-project/#comment-5261:

```
function refreshLangs()
{
    CompileLanguage("data/langs/check.txt",true);
    CompileLanguage("data/langs/try.txt");
}
refreshLangs();

new LangTable(ww);
$I18N::default = ww.getId();
ww.addLanguage("data/langs/check.lso", "ch");
ww.addLanguage("data/langs/try.lso", "tr");
setCoreLangTable("ww");
ww.setDefaultLanguage(0);
ww.setCurrentLanguage(1);
exec("data/langs/languageMap");

function switchLanguage(%language) //use here the #n as it's the order of inclusion
{
	ww.setCurrentLanguage(%language);
	Canvas.setContent(Canvas.getContent());
}
```
nets

https://github.com/TorqueGameEngines/Torque3D/assets/4236451/2ae5e379-dc3d-48b0-9e88-61ab3880d36f

We'll have to see about some cleaner utility methods on that front.

**Comment by ghost** [comment]
> ### 扭矩使用从零开始的索引
> `LangTable`类函数是从零开始索引的（从 0 开始，而不是从 1 开始）。这意味着当您添加语言时，在调用之前构建了以下语言表：`setCurrentLanguage(U32 id)``setCurrentLanguage(1);`
> 
> 编号	名字	文件名
> 0	快递 之 家	中国.txt
> 1	zh	英文.txt
> 当您这样做时，它会自动将“cn”设置为您的默认语言，因为语言表中没有以前的条目，正如它在控制台中报告的那样：`%mytable.addLanguage("cn.txt", "cn");`
> 
> ```
> Language cn [cn.txt] activated.
> ```
> 
> 然后，当您调用它时，它只是将其添加到语言表中，并没有隐式使其成为设置的语言。`%mytable.addLanguage("en.txt", "en");`
> 
> 但是，当您调用时，它会在控制台中显示您从 lang id=0 （cn） 切换到 lang id=1 （en），并显示以下控制台消息：`setCurrentLanguage(1);`
> 
> ```
> Language en [en.txt] activated.
> ```
> 
> ### 缺少工具
> 但可能还有一个更大的问题。根据[此本地化教程](https://torque-3d.readthedocs.io/en/latest/script/localization.html)，您应该使用工具将语言文本文件（cn.txt，en.txt）编译为.lso文件（编译的字符串查找表）。但是 的源文件在 Torque 3D 中丢失，并且该工具没有预编译。`langc``langc`
> 
> 因此，即使您纠正了langID索引使用问题，最大的问题是语言表代码仍然需要编译的语言文件。`.lso`

thanks,i been found to generate “.lso” file yesterday
new engine version method has been changed to link below of this thread（by “CompileLanguage("data/langs/check.txt",true);” 
 function）
https://github.com/TorqueGameEngines/Torque3D/issues/1036#issuecomment-1602832780

**Comment by ghost** [comment]
> _非常_粗略的初稿基于 https://torque3d.org/forums/topic/618-how-setting-languages-countries-into-a-t3d-project/#comment-5261：
> 
> ```
> function refreshLangs()
> {
>     CompileLanguage("data/langs/check.txt",true);
>     CompileLanguage("data/langs/try.txt");
> }
> refreshLangs();
> 
> new LangTable(ww);
> $I18N::default = ww.getId();
> ww.addLanguage("data/langs/check.lso", "ch");
> ww.addLanguage("data/langs/try.lso", "tr");
> setCoreLangTable("ww");
> ww.setDefaultLanguage(0);
> ww.setCurrentLanguage(1);
> exec("data/langs/languageMap");
> 
> function switchLanguage(%language) //use here the #n as it's the order of inclusion
> {
> 	ww.setCurrentLanguage(%language);
> 	Canvas.setContent(Canvas.getContent());
> }
> ```
> 
> 网
> 
>  bandicam_2023-06-22_10-14-28-229.mp4 
> 我们必须在这方面看到一些更干净的实用程序方法。

thanks a lot，your reply just achieved my unit test。

and is there any way to localiztion and international texture and sound ？

then can you replenishment the offical docment as you looks like a specialist of torque 3d ？or share a link of your docment.
the offical docment and guide is not stable for now，as this topic should shows in the docment and save a lot of time.

by the way ：you just mention the bottom of your reply，look forward to your code repository gets better and better. i just noted in it has “Mobile platform” symbol like “arm” 。i like this engine solution because its AAA design language ，yes or not ，but the engine do make the art pipeline and logic architecture easy than the others。but it lack of “mobile and console ”platform，and now documentation and user guide become very early  and its also a problem.
