### ISSUE TITLE
Occlussion stall guard

### ISSUE THREAD

**Issue by lukaspj** [TorqueGameEngines/Torque3D#121]
This issue was created in the [GarageGames Repository](https://github.com/GarageGames/Torque3D) ([Link to original issue](https://github.com/GarageGames/Torque3D/issues/948)).
The issue was originally created by @LuisAntonRebollo and had a total of 1 comments that may contain additional information. The original issue description is pasted below:

Occlusion stall guard use time from frame start and not from `GFXD3D9OcclusionQuery::getStatus` start.

https://github.com/GarageGames/Torque3D/blob/4716f76d5e1855c0672937da15c72001832b2c50/Engine/source/gfx/D3D9/gfxD3D9OcclusionQuery.cpp#L131

``` cpp
   if ( block )
   {  
      while( ( hRes = mQuery->GetData( &dwOccluded, sizeof(DWORD), D3DGETDATA_FLUSH ) ) == S_FALSE )
      {
          //If we're stalled out, proceed with worst-case scenario -BJR
          if(GFX->mFrameTime->getElapsedMs()>4)
          {
              this->end();
              return NotOccluded;
          }
      }
   }
```

**Comment by Azaezel** [comment]
been refactored. @rextimmy for clarity, looking at https://github.com/TorqueGameEngines/Torque3D/blob/ac395775439985cc7332e777485d252055bdb042/Engine/source/gfx/D3D11/gfxD3D11OcclusionQuery.cpp#L56, it would seem the dx11 end doesn't have an explicit test for 'we're taking too long on queries per frame, so just draw it already rather than adding extra load'. that type of check already implicit in the api, a conversion oversight, or did you deem that overly paranoid from a performance standpoint? (if the last, might as well rip it out of the gl side)

**Comment by Azaezel** [comment]
To clarify the thought process a bit behind that 4 millisecond check, the notion is if we're already over half our 8 millisecond/60 fps budget, odds are it's better to eat the render than potentially stall out and make the frame take that much longer. Like said, entirely open to just ripping that on out GL side for parity.

**Comment by rextimmy** [comment]
Either way you want to go, the two backends should be identical, the GL backend originally didn't have this check, it was added later i think, likely the reason the d3d11 end doesn't have it.
