### ISSUE TITLE
Linux : loading `libopenal.so` without having to install `libopenal-dev`

### ISSUE THREAD

**Issue by SuperUserNameMan** [TorqueGameEngines/Torque3D#505]
Hello,

I'm on LinuxMint20.

By default, `libopenal.so` is not present, unless you install the package `libopenal-dev`.

Installing `-dev` package is okay for developers, but players might not have it installed by default. And asking them to do so is not something I want to specify into a Readme.txt that they will not read. ( First time I tried Troque3d, there was no sound, and I thought the engine was just broken ... ).

On my system, `libopenal.so` is just a symlink to `libopenal.so.1` (which was already installed).

So why not try to open ` dlopen("libopenal.so.1") ` directly if ` dlopen("libopenal.so") ` fails ?

https://github.com/TorqueGameEngines/Torque3D/blob/Preview4_0/Engine/source/sfx/openal/linux/LoadOAL.linux.cpp
```` C++
void* openal_library = NULL;

ALboolean LoadOAL10Library(char *szOALFullPathName, LPOPENALFNTABLE lpOALFnTable)
{
    if (!lpOALFnTable)
        return AL_FALSE;

    if (szOALFullPathName)
        openal_library = dlopen(szOALFullPathName, RTLD_LAZY);
    else
    {
        openal_library = dlopen("libopenal.so", RTLD_LAZY);

        if ( openal_library == NULL ) {
            openal_library = dlopen("libopenal.so.1", RTLD_LAZY);
        }
    }

    if (openal_library == NULL) {
        Con::errorf("Failed to load OpenAL shared library. Sound will not be available");
        return AL_FALSE;
    }
````

On some other systems, it might be `libopenal.so.0` or maybe `libopenal.so.2` ... maybe we could add them as fallback too ?

**Comment by SuperUserNameMan** [comment]
I recompiled with the fallback above, and tested after removing the `libopenal-dev` package.
Indeed, loading `libopenal.so.1` directly works on my system ...

**Comment by Azaezel** [comment]
RnD notes thusfar: May very well want to purely stick to "libopenal.so.1" as that is apparently the expected behavior, and it's been pointed out we may want to use RTLD_NOW instead of _LAZY. 

Research notes for folks to mull on:
externals:
https://tldp.org/HOWTO/Program-Library-HOWTO/dl-libraries.html
https://www.gnu.org/software/libtool/manual/libtool.html
org-internals:
https://github.com/TorqueGameEngines/Torque2D/blob/b4cc8826b1b7c2f91037ee08743fbe31b6e3d867/engine/source/platformX86UNIX/x86UNIXOpenAL.cc#L231-L255
