### ISSUE TITLE
data/ui/guis/guiMusicPlayer.gui (0): Cannot re-declare object [GuiMusicPlayer].

### ISSUE THREAD

**Issue by SuperUserNameMan** [TorqueGameEngines/Torque3D#511]
Hello,

---

`data/ui/guiMusicPlayer.gui` is exec twice here :

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/data/ui/UI.tscript#L67-L68

https://github.com/TorqueGameEngines/Torque3D/blob/b6a1acabf813e93979d2feb1f5982bd4f3126e76/Templates/BaseGame/game/data/ui/guis/guiMusicPlayer.tscript#L25-L30

Adding ` if( isObject( GuiMusicPlayer ) ) return; ` at the beginning of ` guiMusicPlayer.gui ` fixes it

**Comment by Azaezel** [comment]
Redundant note, but to be sure the new tech is well understood: As mentioned in #513, we'll be resolving this one by just keeping the file reference via the new queueExec method. That way folks can just do "%this.queueExec("./guis/guiMusicPlayer.gui", true):" in another module, which would override the existing file being exec'd(which is what that true indicates), instead of executing both. This'll help avoid syncing conflicts.
